# AS 4-- Support Vector Machines

Richard Yang

## Data Preparation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Read the data

df_train = pd.read_csv('train_data.csv')
df_test = pd.read_csv('test_data.csv')

df_train.head()

class  BrdIndx  Area  Round  Bright  Compact  ShpIndx  Mean_G  Mean_R  \
0  concrete      1.32   131   0.81  222.74     1.66     2.18  192.94  235.11   
1    shadow      1.59   864   0.94   47.56     1.41     1.87   36.82   48.78   
2    shadow      1.41   409   1.00   51.38     1.37     1.53   41.72   51.96   
3      tree      2.58   187   1.91   70.08     3.41     3.11   93.13   55.20   
4   asphalt      2.60   116   2.05   89.57     3.06     3.02   73.17   94.89   

   Mean_NIR  ...  SD_NIR_140  LW_140  GLCM1_140  Rect_140  GLCM2_140  \
0    240.15  ...       31.15    5.04       0.80      0.58       8.56   
1     57.09  ...       12.01    3.70       0.52      0.96       7.01   
2     60.48  ...       18.75    3.09       0.90      0.63       8.32   
3     61.92  ...       27.67    6.33       0.89      0.70       8.56   
4    100.64  ...       32.05    1.01       0.83      0.75       8.62   

   Dens_140  Assym_140  NDVI_140  BordLngth_140  GLCM3_140  
0      0.82       0.98     -0.10           1512    1287.52  
1      1.69       0.86     -0.14            196    2659.74  
2      1.38       0.84      0.10           1198     720.38  
3      1.10       0.96      0.20            524     891.36  
4      2.08       0.08     -0.10            496    1194.76  

[5 rows x 148 columns]

In [25]:
# (a) print the shape of the data

print('The shape of the training data is: ', df_train.shape)
print('The shape of the testing data is: ', df_test.shape)

The shape of the training data is:  (507, 148)
The shape of the testing data is:  (168, 148)


In [26]:
# b) Remove any rows that have missing data across both sets of data.

df_train = df_train.dropna()
df_test = df_test.dropna()

In [27]:
# c) The target variable (dependent variable) is called "class", make sure to separate this out into a "y_train" and "y_test" and remove from your "X_train" and "X_test". 

y_train = df_train['class']
y_test = df_test['class']

X_train = df_train.drop('class', axis=1)
X_test = df_test.drop('class', axis=1)


In [28]:
# d) Scale all features / predictors (NOT THE TARGET VARIABLE)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### 2. Random Forest Classifier - Base Model:

In [29]:
# a) Start by creating a simple Random Forest only using default parameters. Use the RandomForestClassifier in sklearn. Fit your model on the training data.

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [30]:
# b) Use the fitted model to predict on test data. Use the .predict() method to get the predicted classes.

y_pred = rfc.predict(X_test)

# c) Calculate the confusion matrix and classification report for the test data. 


from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14  0  0  0  0  0  0  0  0]
 [ 1 22  0  2  0  0  0  0  0]
 [ 0  1 13  0  0  1  0  0  0]
 [ 0  5  0 18  0  0  0  0  0]
 [ 0  0  0  0 25  0  0  0  4]
 [ 1  0  1  0  0 13  0  0  0]
 [ 2  0  0  0  0  0 14  0  0]
 [ 0  1  0  5  2  0  0  6  0]
 [ 0  0  0  1  1  0  0  0 15]]
              precision    recall  f1-score   support

    asphalt        0.78      1.00      0.88        14
   building        0.76      0.88      0.81        25
        car        0.93      0.87      0.90        15
   concrete        0.69      0.78      0.73        23
      grass        0.89      0.86      0.88        29
       pool        0.93      0.87      0.90        15
     shadow        1.00      0.88      0.93        16
       soil        1.00      0.43      0.60        14
       tree        0.79      0.88      0.83        17

    accuracy                           0.83       168
   macro avg       0.86      0.83      0.83       168
weighted avg       0.85      0.83      0.83       168



In [31]:
# d)  Calculate predictions for the training data & build the classification report & confusion matrix. Are there signs of overfitting? Why or why not?

y_pred_train = rfc.predict(X_train)
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

[[45  0  0  0  0  0  0  0  0]
 [ 0 97  0  0  0  0  0  0  0]
 [ 0  0 21  0  0  0  0  0  0]
 [ 0  0  0 93  0  0  0  0  0]
 [ 0  0  0  0 83  0  0  0  0]
 [ 0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0 45  0  0]
 [ 0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0 89]]
              precision    recall  f1-score   support

    asphalt        1.00      1.00      1.00        45
   building        1.00      1.00      1.00        97
        car        1.00      1.00      1.00        21
   concrete        1.00      1.00      1.00        93
      grass        1.00      1.00      1.00        83
       pool        1.00      1.00      1.00        14
     shadow        1.00      1.00      1.00        45
       soil        1.00      1.00      1.00        20
       tree        1.00      1.00      1.00        89

    accuracy                           1.00       507
   macro avg       1.00      1.00      1.00       507
weighted avg       1.00      1.00      1.00       507



Are there signs of overfitting? Why or why not?

Yes, there are signs of overfitting. The training accuracy is 1.0, while the test accuracy is 0.83. In addition, there is significant change between precision and recall between the training and test data.

This means that the model is overfitting the training data.

In [32]:
# e) Identify the top 5 features. Feel free to print a list OR to make a plot. 

feature_importances = pd.DataFrame(rfc.feature_importances_,
                                    index = df_train.drop('class', axis=1).columns,  
                                    columns=['importance']).sort_values('importance', ascending=False)

feature_importances.head()

importance
NDVI_40        0.033625
Mean_NIR_40    0.031262
Mean_R_40      0.029328
NDVI           0.028804
Mean_R         0.026188

## 3. LinearSVM Classifier - Base Model:

In [33]:
# Create a simple LinearSVC Classifier only using default parameters.
# a) Use the LinearSVC in sklearn. Fit your model on the training data.

from sklearn.svm import LinearSVC
lsvc = LinearSVC()
lsvc.fit(X_train, y_train)

# b) Use the fitted model to predict on test data. Use the .predict() method to get the predicted classes.

y_pred = lsvc.predict(X_test)

# c) Calculate the confusion matrix and classification report for the test data.

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[13  0  0  0  0  0  1  0  0]
 [ 0 22  1  1  1  0  0  0  0]
 [ 0  2 12  0  0  0  0  0  1]
 [ 1  6  1 15  0  0  0  0  0]
 [ 0  0  0  1 26  0  0  0  2]
 [ 1  0  1  0  0 13  0  0  0]
 [ 2  0  0  0  0  0 14  0  0]
 [ 0  4  0  1  3  0  0  6  0]
 [ 0  0  0  1  6  0  0  0 10]]
              precision    recall  f1-score   support

    asphalt        0.76      0.93      0.84        14
   building        0.65      0.88      0.75        25
        car        0.80      0.80      0.80        15
   concrete        0.79      0.65      0.71        23
      grass        0.72      0.90      0.80        29
       pool        1.00      0.87      0.93        15
     shadow        0.93      0.88      0.90        16
       soil        1.00      0.43      0.60        14
       tree        0.77      0.59      0.67        17

    accuracy                           0.78       168
   macro avg       0.83      0.77      0.78       168
weighted avg       0.80      0.78      0.77       168



c:\Users\Richa\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [34]:
# d)  Calculate predictions for the training data & build the classification report & confusion matrix. Are there signs of overfitting? Why or why not?

y_pred_train = lsvc.predict(X_train)
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

[[45  0  0  0  0  0  0  0  0]
 [ 0 97  0  0  0  0  0  0  0]
 [ 0  0 21  0  0  0  0  0  0]
 [ 0  0  0 93  0  0  0  0  0]
 [ 0  1  0  0 80  0  0  0  2]
 [ 0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0 45  0  0]
 [ 0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0 89]]
              precision    recall  f1-score   support

    asphalt        1.00      1.00      1.00        45
   building        0.99      1.00      0.99        97
        car        1.00      1.00      1.00        21
   concrete        1.00      1.00      1.00        93
      grass        1.00      0.96      0.98        83
       pool        1.00      1.00      1.00        14
     shadow        1.00      1.00      1.00        45
       soil        1.00      1.00      1.00        20
       tree        0.98      1.00      0.99        89

    accuracy                           0.99       507
   macro avg       1.00      1.00      1.00       507
weighted avg       0.99      0.99      0.99       507



Are there signs of overfitting? Why or why not?

Yes, there are signs of overfitting. The training accuracy is 0.99, while the test accuracy is 0.78. In addition, there is significant change between precision and recall between the training and test data.

This means that the model is overfitting the training data.

## 4. Support Vector Machine Classifier + Linear Kernel + Grid Search:

In [35]:
# a) Use SVC from sklearn with kernel = "linear". Run the GridSearchCV using the following (SVMs run much faster than RandomForest):C: 0.01 - 10 in increments of 0.2 (consider using the np.arange() method from numpy to build out a sequence of values) Use 5 cross-fold and the default scoring

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

param_grid = {'C': np.arange(0.01, 10, 0.2)}
grid = GridSearchCV(SVC(kernel='linear'), param_grid, cv=5)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(kernel='linear'),
             param_grid={'C': array([0.01, 0.21, 0.41, 0.61, 0.81, 1.01, 1.21, 1.41, 1.61, 1.81, 2.01,
       2.21, 2.41, 2.61, 2.81, 3.01, 3.21, 3.41, 3.61, 3.81, 4.01, 4.21,
       4.41, 4.61, 4.81, 5.01, 5.21, 5.41, 5.61, 5.81, 6.01, 6.21, 6.41,
       6.61, 6.81, 7.01, 7.21, 7.41, 7.61, 7.81, 8.01, 8.21, 8.41, 8.61,
       8.81, 9.01, 9.21, 9.41, 9.61, 9.81])})

In [36]:
# b) What is the best parameter? What is the best score? .best_params_() : This method outputs to best performing parameters .best_estimator_() : This method outputs the best performing model, and can be used for predicting on the X_test

print("Best parameters: ", grid.best_params_)
print("Best score: ", grid.best_score_)
print("Best estimator: ", grid.best_estimator_)

Best parameters:  {'C': 0.01}
Best score:  0.8089108910891089
Best estimator:  SVC(C=0.01, kernel='linear')


In [37]:
# c) Use the best estimator model: {'C': 0.01} to predict on test data. Use the .predict() method to get the predicted classes.

y_pred = grid.predict(X_test)

# d) Calculate the confusion matrix and classification report for the test data.

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))



[[13  0  0  0  0  0  1  0  0]
 [ 0 22  0  2  1  0  0  0  0]
 [ 0  1 14  0  0  0  0  0  0]
 [ 0  5  0 17  0  0  0  1  0]
 [ 0  0  0  1 25  0  0  0  3]
 [ 0  0  0  0  0 14  1  0  0]
 [ 1  0  0  0  0  0 15  0  0]
 [ 0  3  0  5  2  0  0  4  0]
 [ 0  0  0  1  2  0  0  0 14]]
              precision    recall  f1-score   support

    asphalt        0.93      0.93      0.93        14
   building        0.71      0.88      0.79        25
        car        1.00      0.93      0.97        15
   concrete        0.65      0.74      0.69        23
      grass        0.83      0.86      0.85        29
       pool        1.00      0.93      0.97        15
     shadow        0.88      0.94      0.91        16
       soil        0.80      0.29      0.42        14
       tree        0.82      0.82      0.82        17

    accuracy                           0.82       168
   macro avg       0.85      0.81      0.82       168
weighted avg       0.83      0.82      0.81       168



In [38]:
# e)  Calculate predictions for the training data & build the classification report & confusion matrix. Are there signs of overfitting? Why or why not?

y_pred_train = grid.predict(X_train)
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

[[40  0  0  0  0  0  5  0  0]
 [ 2 87  0  7  0  0  1  0  0]
 [ 0  1 19  1  0  0  0  0  0]
 [ 0  9  0 83  1  0  0  0  0]
 [ 0  1  0  0 70  0  0  0 12]
 [ 0  1  0  0  1 12  0  0  0]
 [ 1  0  0  0  0  0 43  0  1]
 [ 0  3  0  4  2  0  0 11  0]
 [ 0  0  0  0  3  0  1  0 85]]
              precision    recall  f1-score   support

    asphalt        0.93      0.89      0.91        45
   building        0.85      0.90      0.87        97
        car        1.00      0.90      0.95        21
   concrete        0.87      0.89      0.88        93
      grass        0.91      0.84      0.88        83
       pool        1.00      0.86      0.92        14
     shadow        0.86      0.96      0.91        45
       soil        1.00      0.55      0.71        20
       tree        0.87      0.96      0.91        89

    accuracy                           0.89       507
   macro avg       0.92      0.86      0.88       507
weighted avg       0.89      0.89      0.89       507



Are there signs of overfitting?(for Support Vector Machine Classifier + Linear Kernel + Grid Search) Why or why not?

Yes, there are signs of overfitting. The training accuracy is 0.89, while the test accuracy is 0.82. In addition, the precision and recall are very much lower for the test data.

#### 5. Support Vector Machine Classifier + Polynomial Kernel + Grid Search:

In [ ]:
# a) Use SVC from sklearn with kernel = "poly". Run the GridSearchCV using the following: C: 0.01 - 10 in increments of 0.2. degree: 2, 3, 4, 5, 6. Use 5 cross-fold and the default scoring.

param_grid = {'C': np.arange(0.01, 10, 0.2), 'degree': [2, 3, 4, 5, 6]}

grid = GridSearchCV(SVC(kernel='poly'), param_grid, verbose=3, cv=5)
grid.fit(X_train, y_train)

In [40]:
# b) What is the best parameter? What is the best score? .best_params_() : This method outputs to best performing parameters .best_estimator_() : This method outputs the best performing model, and can be used for predicting on the X_test

print("Best parameters: ", grid.best_params_)
print("Best score: ", grid.best_score_)
print("Best estimator: ", grid.best_estimator_)

Best parameters:  {'C': 3.81, 'degree': 3}
Best score:  0.7889730149485537
Best estimator:  SVC(C=3.81, kernel='poly')


In [41]:
# c) Use the best estimator model to predict on test data. Use the .predict() method to get the predicted classes.

y_pred = grid.predict(X_test)

# d) Calculate the confusion matrix and classification report for the test data.

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[13  0  0  0  0  0  1  0  0]
 [ 0 22  0  2  1  0  0  0  0]
 [ 0  2 11  0  0  1  0  1  0]
 [ 0  5  0 17  1  0  0  0  0]
 [ 0  0  0  0 26  0  0  1  2]
 [ 0  0  0  0  0 14  1  0  0]
 [ 1  0  0  0  0  0 14  0  1]
 [ 0  2  0  5  7  0  0  0  0]
 [ 0  0  0  1  3  0  0  0 13]]
              precision    recall  f1-score   support

    asphalt        0.93      0.93      0.93        14
   building        0.71      0.88      0.79        25
        car        1.00      0.73      0.85        15
   concrete        0.68      0.74      0.71        23
      grass        0.68      0.90      0.78        29
       pool        0.93      0.93      0.93        15
     shadow        0.88      0.88      0.88        16
       soil        0.00      0.00      0.00        14
       tree        0.81      0.76      0.79        17

    accuracy                           0.77       168
   macro avg       0.74      0.75      0.74       168
weighted avg       0.73      0.77      0.75       168



In [42]:
# Calculate predictions for the training data & build the classification report & confusion matrix. Are there signs of overfitting? Why or why not?

y_pred_train = grid.predict(X_train)
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))


[[44  0  0  0  1  0  0  0  0]
 [ 0 95  0  1  1  0  0  0  0]
 [ 0  0 20  0  1  0  0  0  0]
 [ 0  1  0 91  1  0  0  0  0]
 [ 0  1  0  0 81  0  0  0  1]
 [ 0  0  0  0  1 13  0  0  0]
 [ 0  0  0  0  0  0 45  0  0]
 [ 0  0  0  0 11  0  0  9  0]
 [ 0  0  0  0  5  0  0  0 84]]
              precision    recall  f1-score   support

    asphalt        1.00      0.98      0.99        45
   building        0.98      0.98      0.98        97
        car        1.00      0.95      0.98        21
   concrete        0.99      0.98      0.98        93
      grass        0.79      0.98      0.88        83
       pool        1.00      0.93      0.96        14
     shadow        1.00      1.00      1.00        45
       soil        1.00      0.45      0.62        20
       tree        0.99      0.94      0.97        89

    accuracy                           0.95       507
   macro avg       0.97      0.91      0.93       507
weighted avg       0.96      0.95      0.95       507





Are there signs of overfitting? Why or why not?

Yes, there are signs of overfitting. The training accuracy is 0.95, while the test accuracy is 0.79. In addition, the precision and recall are very much lower for the test data.

#### 6. Support Vector Machine Classifier + RBF Kernel + Grid Search:

In [ ]:
# a) Use SVC from sklearn with kernel = "rbf". Run the GridSearchCV using the following: C: 0.01 - 10 in increments of 0.2. gamma: 0.01,  0.1, 1, 10, 100. Use 5 cross-fold and the default scoring.

param_grid = {'C': np.arange(0.01, 10, 0.2), 'gamma': [0.01, 0.1, 1, 10, 100]}
grid = GridSearchCV(SVC(kernel='rbf'), param_grid, verbose=3, cv=5)
grid.fit(X_train, y_train)

In [44]:
# b) What is the best parameter? What is the best score? .best_params_() : This method outputs to best performing parameters .best_estimator_() : This method outputs the best performing model, and can be used for predicting on the X_test

print("Best parameters: ", grid.best_params_)
print("Best score: ", grid.best_score_)
print("Best estimator: ", grid.best_estimator_)

Best parameters:  {'C': 2.81, 'gamma': 0.01}
Best score:  0.8284604931081343
Best estimator:  SVC(C=2.81, gamma=0.01)


In [45]:
# c) Use the best estimator model to predict on test data. Use the .predict() method to get the predicted classes.

y_pred = grid.predict(X_test)

# d) Calculate the confusion matrix and classification report for the test data.

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[13  0  0  0  0  0  1  0  0]
 [ 0 21  0  3  1  0  0  0  0]
 [ 0  1 14  0  0  0  0  0  0]
 [ 0  4  0 19  0  0  0  0  0]
 [ 0  1  0  0 26  0  0  0  2]
 [ 0  0  0  0  0 14  1  0  0]
 [ 1  0  0  0  0  0 15  0  0]
 [ 0  2  0  4  3  0  0  5  0]
 [ 0  0  0  1  1  0  0  0 15]]
              precision    recall  f1-score   support

    asphalt        0.93      0.93      0.93        14
   building        0.72      0.84      0.78        25
        car        1.00      0.93      0.97        15
   concrete        0.70      0.83      0.76        23
      grass        0.84      0.90      0.87        29
       pool        1.00      0.93      0.97        15
     shadow        0.88      0.94      0.91        16
       soil        1.00      0.36      0.53        14
       tree        0.88      0.88      0.88        17

    accuracy                           0.85       168
   macro avg       0.88      0.84      0.84       168
weighted avg       0.86      0.85      0.84       168



In [46]:
# e)  Calculate predictions for the training data & build the classification report & confusion matrix. Are there signs of overfitting? Why or why not?

y_pred_train = grid.predict(X_train)
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

[[45  0  0  0  0  0  0  0  0]
 [ 0 96  0  1  0  0  0  0  0]
 [ 0  0 21  0  0  0  0  0  0]
 [ 0  1  0 92  0  0  0  0  0]
 [ 0  1  0  0 81  0  0  0  1]
 [ 0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0 45  0  0]
 [ 0  1  0  0  0  0  0 19  0]
 [ 0  0  0  0  1  0  0  0 88]]
              precision    recall  f1-score   support

    asphalt        1.00      1.00      1.00        45
   building        0.97      0.99      0.98        97
        car        1.00      1.00      1.00        21
   concrete        0.99      0.99      0.99        93
      grass        0.99      0.98      0.98        83
       pool        1.00      1.00      1.00        14
     shadow        1.00      1.00      1.00        45
       soil        1.00      0.95      0.97        20
       tree        0.99      0.99      0.99        89

    accuracy                           0.99       507
   macro avg       0.99      0.99      0.99       507
weighted avg       0.99      0.99      0.99       507





Are there signs of overfitting? Why or why not?

Yes, there are signs of overfitting. The training accuracy is 0.99, while the test accuracy is 0.85. In addition, the precision and recall are very much lower for the test data.

### 7. Conceptual Questions:


#### a) From the models run in steps 2-6, which performs the best based on the Classification Report? Support your reasoning with evidence around your test data. 

The Support Vector Machine Classifier + RBF Kernel + Grid Search performs the best based on the Classification Report. The test accuracy is 0.85, which is the highest among all the models. The precision and recall are also the highest among all the models.

#### b) Compare models run for steps 4-6 where different kernels were used. What is the benefit of using a polynomial or rbf kernel over a linear kernel? What could be a downside of using a polynomial or rbf kernel? 

The benefit of using a polynomial or rbf kernel over a linear kernel is that：

The model can have a better ability to capture non-linear patterns.It also has a higher flexibility in handling the curved or circular patterns of decision boundary which the linear kernel may not be able to capture. Therefore,the model can be more accurate. 

The downside of using a polynomial or rbf kernel is that:

The model will need more computational complexity and sensitivity to hyperparameter tuning compared to linear kernels. Selecting the optimal hyperparameter values can be challenging, and an inappropriate choice may lead to overfitting or underfitting.

#### c) Explain the 'C' parameter used in steps 4-6. What does a small C mean versus a large C in sklearn? Why is it important to use the 'C' parameter when fitting a model? 

The C parameter is the penalty parameter of the error term. It controls the trade off between smooth decision boundary and classifying the training points correctly.

When 'C' is small, the SVM model is more strongly regularized, and the margin between the classes is more likely to be narrower. This can result in a simpler decision boundary that may misclassify some of the training examples, but may have better generalization performance by reducing the risk of overfitting. Smaller values of 'C' are typically used when the training data is noisy, or when there are many irrelevant features.

When 'C' is large, the SVM model is less regularized, and the margin between the classes is more likely to be wider. This can result in a more complex decision boundary that may classify all the training examples correctly, but may have reduced generalization performance by being more susceptible to overfitting. Larger values of 'C' are typically used when the training data is clean, and it is believed that a more complex decision boundary is necessary to capture the underlying patterns in the data.

#### d) Scaling our input data does not matter much for Random Forest, but it is a critical step for Support Vector Machines. Explain why this is such a critical step. Also, provide an example of a feature from this data set that could cause issues with our SVMs if not scaled.

The SVM model is sensitive to the scale of the input data. If the input data is not scaled, the SVM model will be biased towards the features with larger values. Therefore, it is important to scale the input data before fitting the SVM model.

As we can see from the example below, the feature 'Bright' has a much larger range than the feature 'Round'. If the input data is not scaled, the SVM model will be biased towards the feature 'Bright'. Therefore, it is important to scale the input data before fitting the SVM model.

In [14]:
# check the range of bright
print(f'The range of bright is :\n {df_train["Bright"].describe()}')

# check the range of Round
print(f'\n The range of Round is :\n {df_train["Round"].describe()}')

The range of bright is :
 count    507.000000
mean     165.612939
std       63.230806
min       26.850000
25%      127.485000
50%      170.650000
75%      224.825000
max      245.870000
Name: Bright, dtype: float64

 The range of Round is :
 count    507.000000
mean       1.237574
std        0.561988
min        0.000000
25%        0.840000
50%        1.210000
75%        1.565000
max        3.520000
Name: Round, dtype: float64


#### e) Describe conceptually what the purpose of a kernel is for Support Vector Machines.

The kernel is a function that transforms the input data into a higher dimensional space where it may become linearly separable, allowing SVMs to model complex patterns and non-linear relationships in the data and find optimal decision boundaries for classification tasks.