# Tensorflow Introduction

TensorFlow is a graph computing library open-sourced by Google and primarily used for Deep Learning.

In [31]:
import numpy as np
import tensorflow as tf
from tensorflow.python.client import device_lib

In [32]:
#Version
print("TensorFlow version: {}".format(tf.__version__))

#In Tensorflow 2.0, eager execution is enabled by default.
print("Eager execution: {}".format(tf.executing_eagerly()))

TensorFlow version: 2.12.0
Eager execution: True


### System Configuration

In [33]:
#print device list
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 4814119974033590277
 xla_global_id: -1]

In [34]:
tf.config.get_visible_devices(
    device_type=None
)


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [35]:
tf.config.experimental.get_device_policy()

'silent'

In [36]:
tf.config.threading.get_inter_op_parallelism_threads()

0

### Hello World 

In [7]:
message = tf.constant('Hello, TensorFlow!')

In [8]:
message

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, TensorFlow!'>

In [9]:
message.dtype

tf.string

### Constants

In [10]:
t = tf.constant(2)
t

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [11]:
t.shape

TensorShape([])

In [12]:
t.dtype

tf.int32

In [13]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [14]:
t.shape

TensorShape([2, 3])

In [15]:
t.dtype

tf.float32

### Indexing

In [16]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [17]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [18]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [19]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [20]:
#t @ tf.transpose(t)

In [21]:
# Basic constant operations
# The value returned by the constructor represents the output of the Constant op.
a = tf.constant(2)
b = tf.constant(3)

In [22]:
#Prints the nodes of the computational graph within a session. 
print ("a:", a, ", b:", b)

#Perform arithmetic operations 
print ("a + b = %i" % (a+b))
print ("a * b = %i" % (a*b))

a: tf.Tensor(2, shape=(), dtype=int32) , b: tf.Tensor(3, shape=(), dtype=int32)
a + b = 5
a * b = 6


### Numpy Vs Tensorflow

In [23]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [24]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]])>

In [25]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

### Conflicting Types

In [26]:
try:
    tf.constant(1) + tf.constant(1.0)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]


In [27]:
try:
    tf.constant(1, dtype=tf.float64) + tf.constant(1.0)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2]


In [28]:
try:
    tf.constant(1, dtype=tf.float32) + tf.constant(1.0)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

### Variables

In [29]:
a = tf.constant(35, name='a')
b = tf.Variable(a + 5, name='b')

#Perform arithmetic operations 
print ("a + b = %i" % (a+b))
print ("a * b = %i" % (a*b))

a + b = 75
a * b = 1400


In [30]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
v.value()

In [ ]:
v.numpy()

In [ ]:
v.assign(2 * v)

### Ragged Constants

Ragged tensors are the TensorFlow equivalent of nested variable-length lists. They make it easy to store and process data with non-uniform shapes

In [ ]:
digits = tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], []])
print(tf.add(digits, 3))
print(tf.reduce_mean(digits, axis=1))
print(tf.concat([digits, [[5, 3]]], axis=0))
print(tf.tile(digits, [1, 2]))

In [ ]:
words = tf.ragged.constant([["So", "long"], ["thanks", "for", "all", "the", "fish"]])
print(tf.strings.substr(words, 0, 2))

### Switch to GPU

In [37]:
with tf.device("/cpu:0"):
    t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [38]:
t.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [39]:
if tf.config.list_physical_devices('GPU'):
    with tf.device("/gpu:0"):
        t2 = tf.constant([[1., 2., 3.], [4., 5., 6.]])
    print(t2.device)

In [40]:
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)
    print(c.device)

/job:localhost/replica:0/task:0/device:CPU:0


### The tf.function decorator

When you annotate a function with tf.function, you can still call it like any other function. But it will be compiled into a graph, which means you get the benefits of faster execution, running on GPU or TPU, or exporting to SavedModel.

In [ ]:
# Define some operations
@tf.function
def add(x, y):
    return tf.add(x, y)

@tf.function
def multiply(x, y):
    return tf.multiply(x, y)

print ("add node :", add)
print ("mul node :", multiply, "\n")

In [ ]:
tf.function

In [ ]:
a = 2
b = 3

print ("a :", a)
print ("b :", b)


# Run operations with variable input
print ("a + b = %i" % add(a, b))
print ("a * b = %i" % multiply(a, b))

In [ ]:
W = tf.Variable(tf.ones(shape=(2,2)), name="W")
b = tf.Variable(tf.zeros(shape=(2)), name="b")

@tf.function
def forward(x):
  return W * x + b

out_a = forward([1,0])

print(out_a)

In [ ]:
@tf.function
def simple_nn_layer(x, y):
  return tf.nn.relu(tf.matmul(x, y))

x = tf.random.uniform((3, 3))
y = tf.random.uniform((3, 3))

simple_nn_layer(x, y)

### API - Reduce Functions

In [ ]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])

print(tf.reduce_sum(x))  # 6
print(tf.reduce_sum(x, 0))  # [2, 2, 2]
print(tf.reduce_sum(x, 1))  # [3, 3]
print(tf.reduce_sum(x, [0, 1]))  # 6

Reduce Mean compared to Numpy

In [ ]:
c = np.array([[3.,4], [5.,6], [6.,7]])
print(np.mean(c,1))

tf.reduce_mean(c,1)

### Matrices

In [ ]:
# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.

matrix1 = tf.constant([[3., 3.]])
print (matrix1)

In [ ]:
# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])
print (matrix2)

In [ ]:
# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.linalg.matmul(matrix1, matrix2)

product